name: Docker

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
    paths:
      - 'Dockerfile'
      - 'entrypoint.sh'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true


jobs:
  build:
    strategy:
      matrix:
        resolver:
          - snapshot: "lts-20.7"
            ghc: "9.2.5"
          - snapshot: "lts-19.33"
            ghc: "9.0.2"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Image Tags
        id: generate-image-tags
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            tags=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-${{ matrix.resolver.snapshot }}
          else
            tags=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}-${{ matrix.resolver.snapshot }}
          fi
          echo "tags=$tags" >> $GITHUB_OUTPUT
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.generate-image-tags.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GHC_VERSION=${{ matrix.resolver.ghc }}
            SNAPSHOT_VERSION=${{ matrix.resolver.snapshot }}
